default_agent_id: clawhive-main

bindings:
  - channel_type: telegram
    connector_id: tg_main
    match:
      kind: dm
    agent_id: clawhive-main

  - channel_type: telegram
    connector_id: tg_main
    match:
      kind: mention
      pattern: "@builder"
    agent_id: clawhive-builder

  - channel_type: discord
    connector_id: dc_main
    match:
      kind: dm
    agent_id: clawhive-main

  - channel_type: discord
    connector_id: dc_main
    match:
      kind: mention
    agent_id: clawhive-main
